services:
  backend:
    build: ./backend
    container_name: churn_backend
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: churn_frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    restart: unless-stopped